### ISSUE TITLE
Can't download the data

### ISSUE THREAD

**Issue by NinaCalvi** [velocityCavalry/CREPE#2]
Get 404 for the drive, and the `zip` file does not open on a mac

**Comment by velocityCavalry** [comment]
Hi,

Thank you for your interest in CREPE and I'm sorry for the inconvenience! They revoke my drive access after I graduated. Please use [this link](https://drive.google.com/drive/folders/0BxawpCgUevCzfkctQUY4RXI5MzRDNk5YX2FHeVZJNU12NUZCbXVHT3FxQjluSXdGblNwbHM?resourcekey=0-iaePOJrAI_kPGjSok2ITZg&usp=sharing) to download the data, we will fix the script soon as well. Please let us know if there's any problem accessing it! 

Thank you!
